In [393]:
import pandas as pd
import numpy as np
import math
import json

In [394]:
#вариант у меня 10, но строка 9
my_user = 10
v = my_user - 1
k = 4

In [395]:
data = pd.read_csv('data.csv', delimiter = ', ', engine = 'python')
context_day = pd.read_csv('context_day.csv', delimiter = ', ', engine = 'python')
context_place = pd.read_csv('context_place.csv', delimiter = ', ', engine = 'python')
movie_names = pd.read_csv('movie_names.csv', delimiter = ', ', engine = 'python')

In [396]:
data

Unnamed: 0  Movie 1  Movie 2  Movie 3  Movie 4  Movie 5  Movie 6  Movie 7  \
0      User 1       -1        4        1        5       -1       -1       -1   
1      User 2        4        5        2        3        3        4       -1   
2      User 3        4        2        5        4        1        5       -1   
3      User 4        5       -1        2       -1       -1        2        4   
4      User 5        4        3        3        3        5        3        3   
5      User 6        2       -1        3        3        3        3        4   
6      User 7        4        1        4        4        1        4        5   
7      User 8       -1        5        5        3        3        3        3   
8      User 9        1        2        3        1        5        3        3   
9     User 10        5       -1        1       -1        3        3        4   
10    User 11       -1        5       -1        1        5        2        4   
11    User 12        5        4        4       -1        3       -1        5   
12    User 13        1        1        4        5        4        3        5   
13    User 14        3        5        4       -1        1        2        4   
14    User 15        3        5        3        4        4       -1        4   
15    User 16        3        3        5        3        2        2        5   
16    User 17        1        1       -1       -1        4        4       -1   
17    User 18        4        3        3        2        1        5        3   
18    User 19        4        3        5        5        4        4       -1   
19    User 20        2       -1        2        5       -1       -1        1   
20    User 21       -1        2        1        2        3        5        4   
21    User 22        2        4        4       -1        4       -1        4   
22    User 23        5        1       -1        5        5       -1       -1   
23    User 24        5        4        2       -1        2        1        3   
24    User 25        3        1       -1        4        2       -1        4   
25    User 26        1        5       -1        3       -1        2        4   
26    User 27        4        4        3       -1        4        5        3   
27    User 28       -1       -1        4        2        3        2        1   
28    User 29        3        2        4        2        2        2        4   
29    User 30        2        3        5        4        1        3        3   
30    User 31        3        5        4        5        1        3        3   
31    User 32        5        4        5        4        1        5        5   
32    User 33        5        3        4        4        2        1        3   
33    User 34       -1        5       -1       -1        1       -1        5   
34    User 35        4       -1        5        4        2        2        3   
35    User 36        3        2       -1        5        5        1        5   
36    User 37       -1        4       -1        3        1        4        5   
37    User 38        3       -1        1        4        2        3        4   
38    User 39        1       -1        5       -1        1        2        3   
39    User 40       -1        1        1        1        1       -1        4   

    Movie 8  Movie 9  ...  Movie 21  Movie 22  Movie 23  Movie 24  Movie 25  \
0         1        3  ...         2         4        -1        -1         3   
1         5        3  ...        -1         2        -1         3         1   
2         3        5  ...         4        -1         5         4         5   
3         3        2  ...        -1         2         2         2         2   
4         4        5  ...         4         5         2        -1         3   
5         2       -1  ...         5        -1         1         3        -1   
6         2        2  ...         2         5         1         3         4   
7         3        1  ...        -1         3         1         3         2   
8         1

In [397]:
data = data.drop(data.columns[0],axis = 1)#удалили столбец с пользователями
data

Movie 1  Movie 2  Movie 3  Movie 4  Movie 5  Movie 6  Movie 7  Movie 8  \
0        -1        4        1        5       -1       -1       -1        1   
1         4        5        2        3        3        4       -1        5   
2         4        2        5        4        1        5       -1        3   
3         5       -1        2       -1       -1        2        4        3   
4         4        3        3        3        5        3        3        4   
5         2       -1        3        3        3        3        4        2   
6         4        1        4        4        1        4        5        2   
7        -1        5        5        3        3        3        3        3   
8         1        2        3        1        5        3        3        1   
9         5       -1        1       -1        3        3        4        1   
10       -1        5       -1        1        5        2        4        2   
11        5        4        4       -1        3       -1        5        5   
12        1        1        4        5        4        3        5        5   
13        3        5        4       -1        1        2        4       -1   
14        3        5        3        4        4       -1        4        4   
15        3        3        5        3        2        2        5       -1   
16        1        1       -1       -1        4        4       -1       -1   
17        4        3        3        2        1        5        3        4   
18        4        3        5        5        4        4       -1       -1   
19        2       -1        2        5       -1       -1        1       -1   
20       -1        2        1        2        3        5        4        1   
21        2        4        4       -1        4       -1        4        5   
22        5        1       -1        5        5       -1       -1        5   
23        5        4        2       -1        2        1        3        2   
24        3        1       -1        4        2       -1        4        1   
25        1        5       -1        3       -1        2        4       -1   
26        4        4        3       -1        4        5        3        4   
27       -1       -1        4        2        3        2        1        4   
28        3        2        4        2        2        2        4        1   
29        2        3        5        4        1        3        3        2   
30        3        5        4        5        1        3        3        3   
31        5        4        5        4        1        5        5        4   
32        5        3        4        4        2        1        3        1   
33       -1        5       -1       -1        1       -1        5        1   
34        4       -1        5        4        2        2        3        1   
35        3        2       -1        5        5        1        5        2   
36       -1        4       -1        3        1        4        5        4   
37        3       -1        1        4        2        3        4       -1   
38        1       -1        5       -1        1        2        3       -1   
39       -1        1        1        1        1       -1        4        1   

    Movie 9  Movie 10  ...  Movie 21  Movie 22  Movie 23  Movie 24  Movie 25  \
0         3        -1  ...         2         4        -1        -1         3   
1         3         2  ...        -1         2        -1         3         1   
2         5         2  ...         4        -1         5         4         5   
3         2         3  ...        -1         2         2         2         2   
4         5         2  ...         4         5         2        -1         3   
5        -1         1  ...         5        -1         1         3        -1   
6         2        -1  ...         2         5         1         3         4   
7         1         2  ...        -1         3         1         3         2   
8         2         5  ...         3         2         3        -1         1   
9    

In [398]:
similarity_metric = np.zeros(data.shape[0])#создали нулевую матрицу для вычисления метрики сходства
similarity_metric

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [399]:
without_evaluating = -1
for u in range(data.shape[0]): #data.shape[0] - кол-во строк(юзеров)к в массиве data...перебираем всех юзеров
    if (u != v): #чтобы не посчитать метрику сходства для самого себя
        uv_sum = 0 #сумма произведений u на v
        uu_sum = 0 #сумма квадратов u
        vv_sum = 0 #сумма квадратов v
        uv = data.iloc[[u, v]]#извлекаем строку пользователя u и v
        uv = uv.transpose()#транспонируем полученную матрицу (превращаем две строки в два столбца)
        for i,movie in uv.iterrows():#перебираем значения оценок попарно
            if ((movie[u] != without_evaluating) & (movie[v] != without_evaluating)):#если у обоих пользователей этот фильм оценен
                uv_sum += movie[u] * movie[v] #оценка пользователя u для определенного фильма и оценка нашего пользователя умножаются
                uu_sum += pow(movie[u], 2)#возводим в степень
                vv_sum += pow(movie[v], 2)#возводим в степень
        similarity_metric[u] = round(uv_sum / ((math.sqrt(uu_sum) * math.sqrt(vv_sum))), 3)#считаем мерику и округляем до 3х знаков после запятой

In [400]:
similarity_metric

array([0.848, 0.823, 0.766, 0.887, 0.787, 0.9  , 0.796, 0.754, 0.793,
       0.   , 0.872, 0.816, 0.746, 0.806, 0.848, 0.794, 0.826, 0.716,
       0.744, 0.78 , 0.853, 0.779, 0.868, 0.879, 0.725, 0.786, 0.87 ,
       0.839, 0.867, 0.771, 0.818, 0.774, 0.828, 0.777, 0.85 , 0.87 ,
       0.826, 0.852, 0.78 , 0.876])

In [401]:
sim4 = np.argpartition(similarity_metric, -k)[-k:]#функция расставляет в порядке возрастания и мы берем нужные нам последние 4 индекса пользователей

In [402]:
sim4

array([39, 23,  3,  5], dtype=int32)

In [403]:
def means(user):
    l = []#пустой список
    for i in range(data.shape[1]):#data.shape[1] дает кол-во столбцов, т.е. фильмов
        if data.iloc[user][i] != without_evaluating:#пропускаем фильмы, к-е не оценены
            l.append(data.iloc[user][i])#добавляем значение каждого оцененного фильма
    arr = np.array(l)#превращаем список в массив arr
    return np.mean(arr)#вычисляем среднее арифметическое

In [404]:
l = []
for i in range(data.shape[1]):
    if (data.iloc[v][i] == without_evaluating):
        l.append(i)
unrated_films = np.array(l)
unrated_films

array([ 1,  3, 10, 14, 28])

In [405]:
#rui
movie_ratings = {}#создаем словарь
for film in unrated_films:
    sumsimr = 0
    sumsim = 0
    for u in sim4:
        if (data.iloc[u, film] != without_evaluating):
            sumsimr += similarity_metric[u] * (data.iloc[u, film] - means(u))
            sumsim += similarity_metric[u]
    movie_ratings[film] = round(means(v) + sumsimr / sumsim, 3)
movie_ratings

{1: 2.334, 3: 1.671, 10: 2.756, 14: 2.73, 28: 3.188}

In [406]:
result_1 = {}
for i in movie_ratings.keys():
    result_1[f'Movie {i}'] = movie_ratings[i]
result_1

{'Movie 1': 2.334,
 'Movie 3': 1.671,
 'Movie 10': 2.756,
 'Movie 14': 2.73,
 'Movie 28': 3.188}

In [407]:
context_day = context_day.drop(context_day.columns[0], axis = 1)
context_day

Movie 1 Movie 2 Movie 3 Movie 4 Movie 5 Movie 6 Movie 7 Movie 8 Movie 9  \
0       -1     Thu     Tue     Mon      -1      -1      -1     Tue     Sun   
1      Mon     Wed     Mon     Sat     Sat     Thu      -1     Mon     Fri   
2      Tue     Wed     Sat     Tue     Sat     Mon      -1     Thu     Wed   
3      Mon      -1     Wed      -1      -1     Sun     Sat     Mon     Mon   
4      Thu     Fri     Wed     Fri     Mon     Thu     Sat     Tue     Thu   
5      Mon      -1     Tue     Sat     Fri     Fri     Mon     Sun      -1   
6      Thu     Tue     Sat     Fri     Sun     Sun     Fri     Wed     Mon   
7       -1     Sun     Fri     Sat     Fri     Thu     Thu     Tue     Sat   
8      Sat     Sun     Thu     Thu     Tue     Wed     Mon     Tue     Sat   
9      Sun      -1     Tue      -1     Mon     Fri     Thu     Tue     Thu   
10      -1     Sun      -1     Sun     Fri     Thu     Tue     Thu     Thu   
11     Sun     Tue     Sat      -1     Sat      -1     Wed     Wed     Sat   
12     Mon     Tue     Fri     Sat     Fri     Thu     Mon     Sun     Thu   
13     Sat     Fri     Mon      -1     Thu     Wed     Mon      -1      -1   
14     Sat     Fri     Fri     Tue     Sat      -1     Mon     Sat     Fri   
15     Tue     Sat     Thu     Sun     Sat     Wed     Sun      -1     Mon   
16     Fri     Sun      -1      -1     Thu     Fri      -1      -1     Wed   
17     Fri     Sat     Thu     Thu     Mon     Thu     Tue     Sat     Wed   
18     Tue     Sun     Wed     Sun     Sun     Wed      -1      -1     Sat   
19     Wed      -1     Sun     Mon      -1      -1     Mon      -1     Wed   
20      -1     Thu     Thu     Sat     Sat     Thu     Thu     Sat     Fri   
21     Fri     Fri     Tue      -1     Mon      -1     Fri     Wed     Tue   
22     Fri     Mon      -1     Thu     Sat      -1      -1     Wed      -1   
23     Fri     Thu     Mon      -1     Sun     Thu     Sat     Wed     Wed   
24     Thu     Wed      -1     Fri     Mon      -1     Thu     Thu     Fri   
25     Sun     Sat      -1     Wed      -1     Mon     Wed      -1     Wed   
26     Sun     Fri     Thu      -1     Mon     Tue     Wed     Tue     Fri   
27      -1      -1     Mon     Wed     Fri     Mon     Tue     Mon      -1   
28     Sat     Mon     Sat     Sat     Sun     Sun     Thu     Sun     Fri   
29     Sun     Sun     Fri     Wed     Sat     Tue     Fri     Thu     Wed   
30     Fri     Tue     Sat     Thu     Mon     Fri     Mon     Tue     Sat   
31     Mon     Mon     Fri     Sun     Mon     Sun     Fri     Thu     Mon   
32     Sat     Sat     Mon     Tue     Fri     Thu     Wed     Mon     Wed   
33      -1     Sat      -1      -1     Mon      -1     Sat     Wed     Wed   
34     Fri      -1     Sun     Thu     Sun     Thu     Tue     Thu     Sat   
35     Wed     Tue      -1     Sun     Thu     Thu     Sat     Sun     Tue   
36      -1     Fri      -1     Wed     Fri     Mon     Fri     Mon     Fri   
37     Mon      -1     Tue     Sun     Thu     Sun     Fri      -1     Thu   
38     Sat      -1     Mon      -1     Thu     Mon     Mon      -1     Mon   
39      -1     Fri     Tue     Mon     Fri      -1     Sun     Thu      -1   

   Movie 10  ... Movie 21 Movie 22 Movie 23 Movie 24 Movie 25 Movie 26  \
0        -1  ...      Thu      Thu       -1       -1      Sun      Sat   
1       Thu  ...       -1      Sun       -1      Mon      Mon      Fri   
2       Thu  ...      Tue       -1      Wed      Thu      Tue      Thu   
3       Wed  ...       -1      Sun      Fri      Sat      Thu      Sat   
4       Fri  ...      Fri      Fri      Mon       -1      Wed      Mon   
5       Thu  ...      Thu       -1      Wed      Wed       -1      Wed   
6        -1  ...      Tue      Sun      Sun      Tue      Wed       -1   
7       Wed  ...       -1      Sat      Fri      Tue      Fri      Sun   
8       Mon  ...      Wed      Wed      Tue       -1      Fri      Thu   
9       Fri  ...      Thu      Tue      Sun      Thu      Thu   

In [408]:
#Удаляем столбец с юзерами
context_place = context_place.drop(context_place.columns[0], axis = 1)
context_place

Movie 1 Movie 2 Movie 3 Movie 4 Movie 5 Movie 6 Movie 7 Movie 8 Movie 9  \
0       -1       h       h       c      -1      -1      -1       v       h   
1        v       v       v       v       h       c      -1       v       h   
2        v       h       c       c       c       c      -1       h       c   
3        v      -1       h      -1      -1       h       v       v       c   
4        c       c       c       c       v       h       v       v       c   
5        c      -1       c       h       v       c       v       v      -1   
6        v       h       v       c       c       v       c       c       v   
7       -1       h       c       h       h       v       h       h       v   
8        h       c       h       v       h       h       v       c       c   
9        v      -1       v      -1       v       c       h       c       h   
10      -1       c      -1       h       h       h       v       v       c   
11       h       v       h      -1       h      -1       c       v       v   
12       h       c       v       v       c       c       c       h       c   
13       v       c       v      -1       v       v       c      -1      -1   
14       v       c       v       h       v      -1       h       v       c   
15       h       v       c       c       c       c       v      -1       h   
16       v       v      -1      -1       h       c      -1      -1       v   
17       h       h       h       h       h       c       h       h       v   
18       h       c       v       h       c       c      -1      -1       v   
19       v      -1       h       v      -1      -1       h      -1       v   
20      -1       c       c       c       h       c       v       v       v   
21       c       c       h      -1       v      -1       v       c       v   
22       c       v      -1       c       v      -1      -1       v      -1   
23       c       v       v      -1       v       c       c       c       h   
24       c       h      -1       c       v      -1       v       c       v   
25       v       v      -1       v      -1       h       v      -1       c   
26       h       h       v      -1       h       v       v       h       h   
27      -1      -1       v       h       h       h       c       v      -1   
28       v       c       c       v       h       h       c       v       v   
29       c       h       c       c       v       c       h       c       h   
30       v       h       v       h       c       v       v       c       v   
31       c       v       v       v       h       c       h       h       c   
32       h       v       c       v       h       c       c       h       h   
33      -1       h      -1      -1       c      -1       c       c       v   
34       v      -1       h       c       h       v       h       c       c   
35       c       h      -1       c       h       v       h       c       c   
36      -1       v      -1       h       c       h       c       c       h   
37       v      -1       v       h       c       v       h      -1       c   
38       c      -1       v      -1       h       v       v      -1       c   
39      -1       c       v       c       h      -1       c       v      -1   

   Movie 10  ... Movie 21 Movie 22 Movie 23 Movie 24 Movie 25 Movie 26  \
0        -1  ...        h        c       -1       -1        c        c   
1         c  ...       -1        c       -1        c        h        v   
2         v  ...        v       -1        v        v        h        h   
3         h  ...       -1        v        h        h        c        v   
4         h  ...        v        c        v       -1        h        c   
5         c  ...        h       -1        c        h       -1        h   
6        -1  ...        h        c        c        c        v       -1   
7         c  ...       -1        v        c        v        h        h   
8         h  ...        c        v        h       -1        v        h   
9         v  ...        c        v        h        v        c   

In [409]:
unrated_films

array([ 1,  3, 10, 14, 28])

In [410]:
#фильмы, просмотренные дома
home = ['h']
#фильмы, просмотренные на выходных
weekends = ['Sun','Sat']
film_rates = {}
for film in unrated_films:
    points_of_the_film = 0
    for u in sim4:
        if (data.iloc[u, film] != without_evaluating)&(context_place.iloc[u][film] in home)&(context_day.iloc[u][film] in weekends):
            points_of_the_film = points_of_the_film + movie_ratings[film]
    film_rates[film] = points_of_the_film
film_rates

{1: 0, 3: 1.671, 10: 2.756, 14: 0, 28: 0}

In [411]:
best_film = max(film_rates, key=film_rates.get)
movie_ratings[best_film]

2.756

In [412]:
result_2 = {}
result_2[f'Movie {best_film}'] = movie_ratings[best_film]
result_2

{'Movie 10': 2.756}

In [413]:
result = {
    'user': my_user,
    '1': result_1,
    '2': result_2
}

with open('result.json', 'w') as file:
    json.dump(result, file, indent = 4)
    
print(json.dumps(result, indent = 4))

{
    "user": 10,
    "1": {
        "Movie 1": 2.334,
        "Movie 3": 1.671,
        "Movie 10": 2.756,
        "Movie 14": 2.73,
        "Movie 28": 3.188
    },
    "2": {
        "Movie 10": 2.756
    }
}
